FROM lpicanco/java11-alpine
MAINTAINER Ramkumar Chandrasekaran <kumaramc@gmail.com>
ADD target/eshopicle-discovery.jar eshopicle-discovery.jar
ENTRYPOINT ["java", "-jar", "/eshopicle-discovery.jar"]
EXPOSE 8001
