server:
  port: 8080
 
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eshopicle-discovery:8761/eureka

spring:
  application:
    name: eshopicle-gateway
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: http://google.com
        predicates:
        - Path=/employee/**
      - id: consumerModule
        uri: http://microsoft.com
        predicates:
        - Path=/consumer/**