FROM lpicanco/java11-alpine
MAINTAINER Ramkumar Chandrasekaran <kumaramc@gmail.com>
ADD target/eshopicle-gateway.jar eshopicle-gateway.jar
ENTRYPOINT ["java", "-jar", "/eshopicle-gateway.jar"]
EXPOSE 8080
