FROM lpicanco/java11-alpine
MAINTAINER Ramkumar Chandrasekaran <kumaramc@gmail.com>
ADD target/eshopicle-config.jar eshopicle-config.jar
ENTRYPOINT ["java", "-jar", "/eshopicle-config.jar"]
EXPOSE 8002
